- name: install preparation python3 by apt
  become: true
  apt:
    name:
      - build-essential
      - checkinstall
      - libreadline-gplv2-dev
      - libncursesw5-dev
      - libssl-dev
      - libsqlite3-dev
      - tk-dev
      - libgdbm-dev
      - libc6-dev
      - libbz2-dev
      - zlib1g-dev
      - openssl
      - libffi-dev
      - python3-dev
      - python3-setuptools
      - python3.8
      - python3-pip
