---
- name: pre install docker
  become: yes
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

- name: Add Docker GPG apt Key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
    state: present

- name: apt update
  become: yes
  apt:
    update_cache: yes

- name: install docker-ce docker-ce-cli containerd.io
  become: yes
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Add user to docker group
  become: yes
  user:
    name: miro
    groups:
      - docker
    append: yes

# docker compose
- name: get docker compose
  become: yes
  get_url:
    url: https://github.com/docker/compose/releases/download/1.27.4/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose

- name: chmod +x
  become: yes
  file:
    dest: /usr/local/bin/docker-compose
    mode: +x
